### ISSUE TITLE
Create Standardised Data Structure

### ISSUE THREAD

**Issue by kororo** [kororo/excelcy#1]
Convert the current data structure requirements from (data_train, data_config, data_pipes) into more well defined structure, this to ensure easy data integration.

- PDF <-> Python dict <-> ExcelCy (imagine, user load a book of PDF)
- JSON <-> Python dict <-> ExcelCy (by default spaCy JSON data structure)
- YML <-> Python dict <-> ExcelCy (proposed)
- Prodigy <-> Python dict <-> ExcelCy (Prodigy dataset)

This is still WIP.

```yaml
# this is the standardised data structure for ExcelCy for data integration.
data:
  # this is main configuration for the training.
  config:
    # the initial SpaCy data model to begin with. Described in https://spacy.io/models/
    base: en_core_web_sm
    # The absolute/relative path to save the SpaCy data model after training.
    # It is possible to use this to read existing data model and training on top existing one.
    #
    # Example:
    # 1. /data/test-data: Value is absolute path, ExcelCy will automatically ensure "/data" exists
    # 2. test-data: Value is relative, it is always relative to this file directory path.
    # 3. [tmp]/test-data: Value contains [tmp], it always be replaced by either env variable EXCELCY_TEMP_PATH or
    #                     python tempfile.gettempdir() output
    name: /data/test-data
  source:
    S.1:
      # 
      text: Uber blew through $1 million a week. Android Pay expands to Canada. Spotify steps up Asia expansion.
      # this is the source path
      path: /data/test.txt
  # extra pipelines to do pre-train Entity identification
  pipes:
    matcher:
      -
        pattern: Uber
        type: nlp
        entity: ORG
  train:
    S.1.1:
      text: Uber blew through $1 million a week.
      entities:
        - [Uber, ORG]
        - [$1 millon, MONEY]
    S.1.2:
      text: Android Pay expands to Canada.
      entities:
        - [Android Pay, PRODUCT]
        - [Canada, GPE]
    S.1.3:
      text: Spotify steps up Asia expansion.
      entities:
        - [Spotify, ORG]
        - [Asia, GPE]
```
